### ISSUE TITLE
Spontaneous scene error

### ISSUE THREAD

**Issue by hmathers** [vpython/vpython-jupyter#96]
The equivalent of the following code did not initially produce an error, but the next day it did:

```
from vpython import canvas,box
scene = None
def reset(scene=scene):
    if scene: scene.delete()
    scene = canvas()
reset(scene)
scene.camera.follow(box())
```

AttributeError: 'NoneType' object has no attribute 'camera'

I fixed it with:

```
from vpython import canvas,box
scene = None
def reset():
    global scene
    if scene: scene.delete()
    scene = canvas()
reset()
scene.camera.follow(box())
```

**Comment by BruceSherwood** [comment]
This isn't a VPython issue but a Python issue. There really is no way that the first version could have worked, since inside the reset function "scene" is a local variable and "scene = canvas()" has no effect on the global variable "scene", which still has the value None when scene.camera is referenced.
